version: 2

models:
  - name: dago01
    description: "dbt model filtering mtcars with higher than 15 MPG"
    columns:
      - name: row_names
        quote: true
        description: "Car names"
        data_type: varchar
        tests:
          - unique
          - not_null

      - name: mpg
        quote: true
        description: "MPG of car"
        data_type: float
        tests:
          - not_null
      
      - name: cyl
        quote: true
        description: "Cylinders of car"
        data_type: int

      - name: disp
        quote: true
        description: "Displacement of car"
        data_type: float
        
      - name: hp
        quote: true
        description: "Horsepower of car"
        data_type: int
        tests:
          - not_null
      
      - name: drat
        quote: true
        description: "Drag coefficient of car"
        data_type: float
      
      - name: wt
        quote: true
        description: "Weight of car"
        data_type: float
      
      - name: qsec
        quote: true
        description: "Quarter-seconds of car"
        data_type: float

      - name: vs
        quote: true
        description: "Vendor of car"
        data_type: int

      - name: am
        quote: true
        description: "Aspiration of car"
        data_type: int

      - name: gear
        quote: true
        description: "Gear of car"
        data_type: int
        tests:
          - not_null
        
      - name: carb
        quote: true
        description: "Carburetor of car"
        data_type: int
  
  - name: dagoagggears
    description: "dbt model aggregating mtcars by gears"
    columns:
      - name: gear
        quote: true
        description: "Gear of car"
        data_type: int
        tests:
          - not_null
        
      - name: total
        description: "Number of cars in this gear"
        data_type: int

      - name: min_mpg
        description: "Minimum MPG of cars in this gear"
        data_type: float
      
      - name: max_mpg
        description: "Maximum MPG of cars in this gear"
        data_type: float

      - name: avg_mpg
        description: "Average MPG of cars in this gear"
        data_type: float
      
      - name: min_hp
        description: "Minimum HP of cars in this gear"
        data_type: float

      - name: max_hp
        description: "Maximum HP of cars in this gear"
        data_type: float
      
      - name: avg_hp_dago
        description: "Average HP of cars in this gear"
        data_type: float